[metadata]
name = cashlyctl
version = 0.1.0
description = Cashly CLI tool
author = goCashly
license = MIT

[options]
packages = find:
install_requires =
    textual>=0.58
    rich>=13.7
    httpx>=0.27
    python-dotenv>=1.0
    pyfiglet>=0.8.post1
    click>=8.1
    typer>=0.16

[options.package_data]
* = *.tcss, *.json

[options.packages.find]
include = cashlyctl*
exclude = FILES, tests
